package AdventOfCodeKotlin.puzzles.EverybodyCodes2025

import AdventOfCodeKotlin.util.Adjacent.Companion.buildRouteTable
import AdventOfCodeKotlin.util.Graph.Companion.buildGraph
import AdventOfCodeKotlin.util.Node
import kotlin.math.ceil
import kotlin.math.floor
import kotlin.math.roundToInt
import kotlin.math.sqrt

class Quest20 {
    companion object {
        fun part1() {
            val input = """
                TTT#TT#TT#TTTTTTT#TTTTTTT
                .TTTTTTTT#TT#T#TTT#T#TTT.
                ..TTTTT####TTTT#TTTTTTT..
                ...T#TT#T#TT#T##TT#TT#...
                ....T#TT##TTTT##TTTTT....
                .....#T#TTTTTT#TT#TT.....
                ......TT#T#TT#TTTTT......
                .......TTT####TTTT.......
                ........T#T#TTTTT........
                .........T##TTTT.........
                ..........TTTTT..........
                ...........TTT...........
                ............T............
            """.trimIndent().lines().map { it.toList() }
            val graph = buildGraph(
                input, ::Node,
                includePredicate = { it == 'T' },
                neighborPredicate = { a: Node<*>, b: Node<*> -> a.y == b.y || (a.x % 2 == a.y % 2) }
            )
            println(graph)
            println(graph.values.sumOf { it.neighbors.size } / 2)
        }

        fun part2() {
            var rawInput = """
                TTT#TTTT#TT#TT#TTT#TTT#TTTT#TTTTTTTT#TTT#TTT#T#TTTT#TTTTTTTT#TT#TTT#TTT#TT#TTTTT#TTTT#TTTT#TTTTTTTTTTTTTT#T#TTTTT#TT#TT#TTTTT#T#TTTTT#TTTTTTTT#TTTTTTT#TTTTT#T#
                .#TTTT#TTTTTTTTTTTTTTTTTTTTTTT#TTTTTTT#TTTTTTTTTT#TTTT#TTT#TTTTTTTTTTTTTTTTTT#TTTTTTTTTTTTTTT#TT#TT#TT#TTTTTTTTTTTTTTTTTTT#TTTTTTT#TTTTT#TT#TTTTTT#TTTTT#T#TTT.
                ..T#TTTT#TTTTTTT#TTT#TTTTTTTTTTT#TTTTTTTT#TTTTTTTTTTTTTTTT#TT#TTTTT#TTTTTTT#TTTTTTTTTTTT#TTTTTTTTTT#TTTTTTTT#TTTTTTTTTTTTTTT#TTT#TTTT#TTTTTTTTT#TTTTTTTTTTTT#..
                ...TTTTTTTTTT#TTTT#TTTTTT#TT#TTTTT#T#TT#TTTTT#T#T#TTTTTTTT#TTTTTTTTTTT#TTTTTTTTTT#TTT#TTTTTTTTTTTTT#TTTTTT#TTTT#TTT#TTTTTT#TTT#TTTTTTTTTTTTT#TTTTTTTTTTTTTTT...
                ....T#TT#T#TTTTTTTTTTT#TTTTTTT#TTTTTTTTTTTTTTTTTTTTT#############TTTTTTTT#TTTTTTTTTTTTTTTTTTT############TTTTTTTTTTTTTT#TTTTTTTT#T#T#TTTTT#TTT#TTTT#TT#TT#T....
                .....TTTTTTTT#TT#TT#TTTTTTTTTTTTT#TTTTT#T#TT#TTTT###################TTTTTTTT#TTTTTTTTTTTTT###################TTTTTT#TTTTTTT#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.....
                ......TTTTT#TTTTTTTTTTTT#T#TT#TTTTTT#TTTTTTTTTT######TTTTTTTTTTT#######TT#TTTTT#T#T#TTT#######TTTTTTTTTT#######TTTTTTTTTTTTTTTTTTTTTTTT#TTTTTT#TTTTTTTTT#......
                .......#T#TTTTT#TTTTTT#TTTTTTTTTT#TTTTTTTTTTT######TTTTTTTTTTTTTTT######TTTTTTTTTTTTT######TTTTTTTTTTTTTTTT#####TTT#TT#TTTT#TTTT#TT#TTTTT#TT#TTT#TTTT#TT.......
                ........TTTT#TTTTTTTTTTT#T#TTTTTTTTTTTTTTTTT#####TTTTT######TTTTTTTT#####TTTT#T#TTTT#####TTTTTTTT######TTTTTT#####TTTTTTT#TTT#TTTTTTTTTTTTTTTTTTTT#TTTT........
                .........T#TTTTT#TT#TTTTTTTTTTT#T#TTTTT#TTT#####TTTT###########TT#TTT#####TTTTTTTTT#####TT#TTTT##########TTTTT####TTTT#TTTTTTTTTT#TTTT#TTTTTTT#TTTTTTT.........
                ..........TTTT#TTTTTTTTTTTTTTTTTTTTTTTTTTTT####TTTT####TTT#####TTTTTTT####TT#TTTTTT####TTTTTTT######TTT###TTTTT####TTTTTTTTTTTTTTTTT#TTTT#TT#TTTT#TT#..........
                ...........T#TTTTTTTTT#TTT#TT#################TT#TT#############TTTTTTT####TTTT#TTT####TTTTTTT############TTTTT##################TTTTTTTTTTTTTTTTTTT...........
                ............TTTT#T#TTTTTTTTTT#################TTTTT############TTT#TTTT####TTTTTTT####TTT#T#TT############TTTTT##################TTTT#TTTTTTTTTTTTT............
                .............TTTTTTTTTT#TTTTT####TTTTTTTTTTTTTTTTTTT##########TTTTTTTTT####T#T#TTT####TTTTTTTTT##########TTTTT#####TTTTTTTTT#####TT#TTTTTTT#TT#TTT.............
                ..............T#TTTTTTTTTT#TTT####TTTTTTTTT#####TTTTTT######TTTTTTTTTTT####TTTTTTTT####TTTT#TTTTT######TTTT#TT####TTTTTTTT######TTTTTT#TTTTTTTTTT..............
                ...............TTT#TTTTTTTTT#TTT#################TT#TTT#T#TTTTTTT#TT#TT####TT#T#TTTT####TTTTTTTTTTT#TTTTT#TTTT#####TTT#########TTTT#TTTTTTTTTTTT...............
                ................TTTTTTT#TTTTTTTTTTT###############TTTT#T#T#TTT#TTTTTTT####TTTTTTTTTT####TTTTTT#TTT#TTT#TTTT####################TTTTTTT#TT#T#TT#................
                .................TTTT#TTTT#TT#T#T#TTTTTTTTTTTTTTTTT#TTT#T#TT#TTTTTTT#####TTTT#TT#TTT######TTTTTTTTT#TTTTTTT###################TTT#TT#TTTTTTTTT.................
                ..................#TTTTT#TTTTTTTTTTTTT#TTTTT#####TTTTTTT#TTTTTTTTT######TTTTTTTTTTTTTT######TTTTTT#TTTTTTTTT#####TTTTTTTTTTTTTTTTTTTTTTTT#TTT..................
                ...................TT#TTTTTTTTTT#TT#TTTTTT#TT#########T#TTTT#TT#######TTTT#TTTTT#T#TTTT########TTTT#TTT########TTTT#TTTTTTTT#TTTTTTT#TT#TTT#...................
                ....................TTTTTTTTT#TTTTTTTT#TTTTTTTTT#######TTT#TTTT#####TTTTTTTTTTTTTTTTT#TTTT#####TTT#TTTT#######TT#TTTTT#TTT#TTT#TT#TTTTTTT#T....................
                .....................TTTTTTTTTTTTTTTTTTTT#T#TTTT####TTTTTTTTT#TT####TT#T#TTTT#TTTTTTTTTTTT####TTTTT#TTTTTT####TTTT#TTTTT#TTTTTTTTTT#TTTTTT.....................
                ......................#TTTTTTTTTTTT#T#T#TTTTT#TT####TTTTTT#TTTTT####TTTTTT#TTTT#T#TT#TT#TT####TTTT#TTTTTTT####TTTTTTTTTTTTTTTTTTT#TTTT#TT......................
                .......................TT#T#TT#TT#TTTTTTTTTTTTTT####TTTTTTTTT#TT####TTTT#TTT#TTTTTTTTTTTTT####T#TTT#TTTTTT####TT#T#TTTTTTT#TTT#TTTT#TTTT.......................
                ........................TTTTTTTTTTTTT#TTTT#TTTTT####TT#TTTTTTTTT####TTTTTTTTTTTTTTTTTTTTTT####TTTT#TTTTTTT####TTTTTTT#TT#TTT#TTTT#TTTT#........................
                .........................TTTT#TTTTT#TTTT#TTTT#TT####TTTT#T#T#TTT#######T#T#T#T#T#T#T#T#T######TTTTT#TT#T#T####TTTT#TTTTTTTTTTTTTTTTTTT.........................
                ..........................#TTTTT#TTTTT#TTTTTTTTT####TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT#TTTTTTT####TTTTTTTTTT#TTTTT#TTTTT#..........................
                ...........................TT#TTTTTTTTTT#T#TTTTT####TT#TTTTTT#####################################TTT#TTTT####TTTT#TTT#TTTT#TTTTT#TT...........................
                ............................TTTTTTTTTTTTTTTTT#TT####T###TTTTT#####################################TTTTTTTT####TT#TTTTTTTTTTTTTTTTTT............................
                .............................TTTTTTTTTTT#TTTTTTT####TT##TTTTT#####TTTTTTTTTTTTTTTTTTTTTTTTTTT#####T#TTTTTT####TTTTT#TTTTTTTTTT#TTT.............................
                ..............................TTTT#T#TTTTT#TTTTT####TTTTT#TTTT#####TTTT#TT##TTTETTT##TTTTTTT#####TTTTT###T####TT#TTTT#T#TT#TTTTTT..............................
                ...............................T#TTTTTTTTTTTT#TT#######T###T#TT####TTTTTTTT##TTTTT##TT#TTTTT####TTT#TTT#T#####TTTTTTTTTTTTTTTTT#...............................
                ................................TTTTTTT#T#TTTTTT####T##TTTTTTTTT#####TTTTTTT#######TTTTTTTT#####TTTTTTTTT####TT#T#TT#TTTT#T#TTT................................
                .................................TTT#TTTTTTTTT#T####TTTTTT###TTTT########TTTTTTTTTTTTTT#######TTTTTT###TT####TTTTTTTTTT#TTTTT#.................................
                ..................................#TTTTTTTTTTTTTT####T###TT##TTTTTT########TTTTTT#TTT#######TTTTTTTT###T#####TTTTTTT#TTTTT#TT..................................
                ...................................TTT#TTT#T#TTTT#####T###TTT###TTTT########TTTTTTT########TTTTTTTTTTTT#####TTTTTT#TTTTTTTTT...................................
                ....................................#TTTTTTTTT#TTT#####TTTTTT####TTTT########TTTTT#####TTTTTT#TT###TTT#####TTTTTTTTTTTTT#TT....................................
                .....................................T#TTTTTTTTTTTT#####TT##TTTTTT####TTTT####TTT###TTTTTTTTTTTT###TT#####TTTT#TTTTTT#TTTT.....................................
                ......................................TTTT#TTTTT#TTT#########TTTTTT###TTTTTTTTTTTTTTTTTTTTT###TTTTT######TTT#TTTT#TTTTT#T......................................
                .......................................#TTTTTT#TTT#TTT######TTT#####TT##TTTTTTTTTTTTTTTTT#T###TTT######TTT#TTTTTTTTTTTTT.......................................
                ........................................T#TT#TTTTTTTTTT#######TTT##TTT###TTTT#TT#TTTT###TTTTT#T#######TTTTTT#TTTTTTTTTT........................................
                .........................................TTTTTTT#TT#T#TTTT########TTTTTTTTTTTTTTTTT#TTTTTTT#########TTTTTT#TTTT#TT#TT#.........................................
                ..........................................TTT#TTTTTTTTTTTTTT############TTTTTTTTTTTTT############TTTT#TTTTTTTTTTTTTTT..........................................
                ...........................................#TTT#TTTTT#T#TTTTTTTT#############################TTTTTTTTTTT#T#TTTTTTTTT...........................................
                ............................................T#TTT#TTTTTTTTTTTTTTTTTTT####################TTTTTTTTTT#TTTTTTTTTT#TTT#............................................
                .............................................TT#TTTTT#T#TT#TT#TTTTTTTTT#####TTTTTTT#####TTTTTTTTT#TTTT#TTTTTTTTTTT.............................................
                ..............................................TTTTTTTTTTTTTTTTTTTT#TTTT#####T#TTTTT#####T#T#TTT#TTTTTTTT#TTTTTT#T..............................................
                ...............................................#TTT#T#TT#TTTTTTTTTTTTTT#####TTT#TTT#####TTTTTTTTTT#TTTTTTT#T#TTT...............................................
                ................................................TTTTTTTTTTTT#TT#TTTTTTT#####TTTTT#T#####TTTTTTTT#TTTT#TT#TTTTTT................................................
                .................................................TTTTTTTT#TTTTTTTTT#TTT#####TT#TTTT#####TT#TT#TTTT#TTTTTTTTTT#.................................................
                ..................................................TT#TTTTTTT#TTT#TTTTTT#####TTTTT#T#####TTTTTTT#TTTTTTTT#TTTT..................................................
                ...................................................TTT#TTTTTTTTTTT#TTTT#####TTTTTTT#####TTTTTTTTTTTTTTTTTTTT...................................................
                ....................................................TTTTT#TTTTTTTTTTTTT#####TTTT#TT#####TTTTTTTTTT#TT#TTTT#....................................................
                .....................................................TTTTTTTTTT#############TTTTTTT############TTTTTTTTTTT.....................................................
                ......................................................TTTTTT################T#TTTTT###############TTTTTTT......................................................
                .......................................................#####################TTTT#TT##################TT#.......................................................
                ........................................................TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT........................................................
                .........................................................#TTTTTTTTT#T#TTTTTTT#TT#TTTTTTTTTTTTTTTT#TTTT.........................................................
                ..........................................................T#TT#TTTTTTTT#TTTTTTTTTTTTTTT#TTTTTT#TTTT#T..........................................................
                ...........................................................TTTTTT#TTTTTTTTTT#TT#TT#TT#TTTT#TTTTT#TTT...........................................................
                ............................................................#TTTTTTT#TTTTTTTTTTTTTTTTTTTTTTTT#TTTTT............................................................
                .............................................................T#TTT#TTT#TT#T#T#TT#T#T#TT#T#TTTTTTT#.............................................................
                ..............................................................TT#TTT#TTTTTTTTTTTTTTTTTTTTTT#TT#TT..............................................................
                ...............................................................TTTTTTT#TTTTTTTTTT#TT#TTTTTTTTTTT...............................................................
                ................................................................TTTT#TTTTTT#TTTTTTTTTT#TT#TTTTT................................................................
                .................................................................#TTTTT#T#TTTT#TTTTTTTTTTTTT#T.................................................................
                ..................................................................TT#TTTTTTTTTTT#TTTT#TTTT#TT..................................................................
                ...................................................................TTTTTTTTTTTTTTTTTTTTTTTTT...................................................................
                ....................................................................TTTTTT#TTTTTTT#TTTT#TT#....................................................................
                .....................................................................T#T#TTT#TT#TTTTT#TTTT.....................................................................
                ......................................................................TTTTTTTTTTTTT#TTTTT......................................................................
                .......................................................................TT#TT#TTTT#TTTTTT.......................................................................
                ........................................................................TTTTTT#TTTTTTT#........................................................................
                .........................................................................#TTTTTTT#TT#T.........................................................................
                ..........................................................................T#TTTTTTTTT..........................................................................
                ...........................................................................TTT#TTTTT...........................................................................
                ............................................................................TTTTT#T............................................................................
                .............................................................................TTTTT.............................................................................
                ..............................................................................#TT..............................................................................
                ...............................................................................S...............................................................................
            """
            val input = rawInput.trimIndent().lines().map { it.toList() }

            var tempStart: Node<Char>? = null
            var tempEnd: Node<Char>? = null
            val graph = buildGraph(
                input, ::Node,
                includePredicate = { it in listOf('T', 'S', 'E') },
                neighborPredicate = { a: Node<*>, b: Node<*> -> a.y == b.y || (a.x % 2 == a.y % 2) },
                callbacks = mapOf(
                    'S' to { _: Char, node: Node<Char> -> tempStart = node },
                    'E' to { _: Char, node: Node<Char> -> tempEnd = node }
                )
            )
            val start = tempStart!!
            val end = tempEnd!!

            val routeTable = buildRouteTable(listOf(start))
            println(routeTable[start]?.get(end))

        }

        fun part3() {
            var rawInput = """
                TTT#TTTTTTT#TTT#TTTTTTTTTTTT#TT#TTTTTTTTTT#TTTTT#TTTTTT#TTTTTTTTTTTTTTTTT#T#TTTTTTT#TTTT##TTTTTTTT##TTTT#TTT#TTTTTTTT#TTTTTTTTTT##TTTTTTTT#T#TTTT#T#TTTTTT##T
                .T#TTTTT#TTTTTTTTTT##TTTTT#TTT#T#TTTTTTTT#TTTTTTTT#TTTTTTTT##TTT#TTTT#TTTTTTT#TTTT##TTT#TTTTTT#T#TTT#TTTTTTT##TTTTTT#T#TTT#TTTT#TTTTTTTTTTTT#TTTTTTTTTTTTTT#.
                ..#T#TTT#TTT#TTTTTT#TTTTTTTTTTT#TTT##TTTTTTTTT#TTTTTTTTTTTTTTTTTTTTT#TT#T#TTTTTTTTTTTTT#TT#TTTTTTTTTTTT#TTT#TTT##TTTTT##T##TTTTTTTT#TTTT####TTTTT##TTTTTTTT..
                ...TTTTTTT#TTTT#T#TT#TTTTTTT#TTTTTTTTTT##TT##TTTTTTTTTT#T#T#TT#TTT#T##TTTTTTTTT#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT#TTTT#TTTT##TTTT#TTTTTT#TTTTTTTTTTT###TT#T#...
                ....TTTTTTTTTT#TTTT###TTTTTTTTTT#T#TT#TTT##TTTTTT##TTTTTTTT##TTTTTTTTTTT#TTTT#TTTT##TTT#TTT#T#TTT#T#T##TTTTTTTTTT#TTT#TT#TTTTTTTTTTTTTT#TTTT##TTT#TT#TTTT....
                .....T#T#T#TTTTTT#T#T#TTT#TTT#TT#TT#TTTTTTTTT#TT#TTTTTTTT##T#T#T#TTTTTT#TTT#TTTTTTTTT#T#TTTT#TTTTTTTTTT#TTTT#TT####TTTT#T#TTTTTTTTTT#TTT#TTTTTTTTTTTTTT#.....
                ......#TTT#TT#TTT#T#TTTTTTTTTTTT##TTTTTTTTT#TTTTTTT#T##TTTTT#TTTT#TTTT#TTTTTTTTTTTTTTTTTT#TTTTTT###TTTTTTT#TTTTTTT#TT#TTTTT#TTTT##TTT#T##TTTTTTTTTTTT##......
                .......T#T#TTTTTTTT#T#TTTTT#T#T##T#TTTTTT#TTTTTTTTTTTT##TTTT#TTTTTTTTTT##TTT#TTTT#TTTTT#TTTTTTT#TTTTTTTTTT#TTTTTTTTTTTTTTTTT#TTTTT#T#####TTTTTTTTTT##T.......
                ........T#T#TT#TTT#TTTTTTTTTT#TTTTT#T##TT#TTTTTTTTT##T#T#TTTTT#TTTTTTTT#TTTT#TT#TT#TTT#TT#TTTTT#TTTTTT##TTTTTTTTTTTT#TTTTTTT#TTTTTTT##TTT###T#T#TTTTT........
                .........#TTTTTTTTTTTTT#TTTTTTTTTTTTTTTTTTTT#TTTTTT#TT#TTTTTT##TTTTTT##TT#TTT#TTT##TTTTTT##TTTTTTT#TTTTTTT#TTTT#T#T#TTTTTTTTTTT#TTTTT#T#TTTTTTTTTT#T.........
                ..........TTTTTTTTT##T#T#T##TT#TTTTTT#TTTTT###TTTT##T#TTTTTTTTTTTTTTTTTT#TTTTTT##TTTTTTTT#TTTT#TTTT#TTTTT#T#TTTTTT#TTTT#TTTT#TTTTT#TTTTTTTTT#TTT#T#..........
                ...........TTTT##TTTTTTTTTTTTTTTTTT#TTTTTTTTTTT##TTTTTTTTT#T#TTT#TTTTTT#TTTTTTTTTTTT##TTT#TTT#TT##TTT#T#TTT#TTTT#TTTTTTTT#TTT#TTTT#TT##TTTTTT#T#TT...........
                ............T#TTTT##TTTTTTTTT#T#TT#TT##TTTTTT##T#TTTTTTTTTTT#TTTTTTTTTTTTTT#TTTTTTTTTTTTTTTTTT##TTTTT#T##TTTTT#TTTT#T#TTTTTTTTTTTT#TT##TTTTTTT#TT............
                .............T#TTT#TTTTTTTTTTT#TTTT#TTTT##TTTTT#TTTTTT###TTTT#TTTTT#T#TTTTTTTTTT#TTTTTTTT#T#TTTT#TTTT#TT#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT#TTTT.............
                ..............TTTTTTTTTTT#TTTTTTTTTTTTTTT#TTTTTTTTTTTT#TTTTTTTTTTTTTTTT#T#T#TTTTTTTT#TTTTTTTT#TTTT#TTTTTTTT#TTT#TTTTTTT#TTTTTTTTTTTTTTT###T#TTT..............
                ...............TTTTTT##TTTTT#T#TTTTTTTT#TT#TTT#####T#T#T#T#TTTTTT#T#T##T###TTTTTTTTTTT#TTTT##TTTTTTTTTTT#TTTTTT#TTT#TTT#TT##TTTTTTTT#T#TTT#TT#...............
                ................TTT#T#TTT###T#TTTTTT#TT#TTTTTTTT#TT##TTTTTTTTTTTTTTTTTTT#TT#TTT##TTTT#TTTTT###TTT#T#T##TTTTT#TTT#T#TTTTTTTTT#TT#TTT#TTTTTT#TT................
                .................TTTTTTTT#T##TT#TTT#TTT#TTTTTTTTTTTT#T#TT#T#TTTTTTTTTT#TTT#T###T##TT#TT#TTTTTTTTTT#TTTTTTTTTTTTT#TT#TTTTTTT#TTTTTTTTTTTT#T#T.................
                ..................TTTT#TTTTTTTTTT#TTTTTTTTTTTTTTT#TTTTTTTTTTT#TTTT##TT#TTTTTT#TTT#TTTTT#TTTT#TT#TTT#TTTTTTTTTTTT#TTTTTTTTTTTTTTTTTTT#TTTTTT..................
                ...................TTT##TTTTTT##TT#TTTTT#TT##TT#T#TTTTT#TTT#TTT#TTTTT#TTTTTTTTTTTTTTT###TTTT#TTTTT#T#TT#TTTTTTTTTTTTT#TTTTTTTTTTTTT#TTTTT#...................
                ....................#TTTTTT#TTTTTTTTT#TT#TTT#TTTT#TTTTTTTTTTTTTTTTTTTTTTT#TTTTTTTT#TT#T#T##TTTTTT#TTTTTTTT#TTT#T#TTTTT#TTT#TTTTTTT#T###TT....................
                .....................TTTTTT#T#TTTT#TTTT#TT#TTTTTTTTTTTTTTTTTTTTTT#TTTTTTT##TTTTTTTTTTTTTTTTT#TTTT#TT#T###TT#TT#TT##TTTTTTTT#TTTTTTTTTTTT.....................
                ......................T##TTT#TTTTT#TTT#TTT#TTTTTT#TTTTTTTTTTTTTTT#TTTTTTTTT##T#TT#TTT#TTT#TTTTTTTT#TTTTTTTTTTTTTTTT##TTTTTTTTT#TT#TTTTT......................
                .......................T#TTTTTTTTTT##TTTTTTTTTT#TTTTT#TTTTTTTTTTTT#TTT#TTT#TTTTTTTTT#TTTTTTTTTTTTTTTTTTTT#TTTTT#TTTTTTTTTT#TTTTTT#TTTT.......................
                ........................T#T#T####TT#TTTTTT#TTTTTTTT#TTTTT#TTTTTTTTTT#TTTTT#T#TTT#TT#T##T#T#TTTTTTTTTTT#TTTT#T#TTTTTTTT#T#TT##TT#TTTTT........................
                .........................TTTTTT#T###TTTTTTTTTT#TTTTTT##TTTT#TTT#TTTTTTTTTTTTET#TTTT#TTTTTTTTT##TTTTTTT##T#TT#TTTTT###TTTT#TTTT#TTTTT.........................
                ..........................TTT#TTTTTTTTTTTTTTTTTTTTTTTTTTTTT##TT#TT#TT#TTTT#TTTTTTTTTTTTTTTTTTT#TT#TT#TTTTTTTTTTTTTTTTTTTTTTTTTT#TT#..........................
                ...........................TTTT#TTTTTT#TTTT#TTT##TT#TTTTTT#TTTTTTTTT#TTTTTTTTTTTTT#TTTTTTTT#TTTTT#TTTTTTTTTTTTTTTTT#TT##TT#TTT#TTT...........................
                ............................TTTTT#TT#T##TTT#T#T#TTTT#TTTTTTTTT#TTT#TTTTTTTTTTTTTTT#TTTTTT#TT#TTT#TTTT#T#TTTTTTTTTTT#TTTTT#TTTT#TT............................
                .............................TTTT#TT#TTTTTT#TTTTTTTTT#T#TTTTTTT#TTTTTT#T#TTTT#T#TTTTTTTT#TT##TTTTTTTTTT#TTTTTTTT#TT#T#T#T#TTTTTT.............................
                ..............................TTT#TTTTTTTTTTT#T#TT#TTTTTTTTTTT#TTTTT#TT#TTTTTTTTTTT#TTTTTTTTT#TTTT#TTT#TTTTT#TTT#TTTTTTTTTTTTTT..............................
                ...............................TTT#TTTTT#TTTTTTTTTTTTTT#T#TTTTTT#T#TT#T#T#TTTTTT#T#TT#T#T#TTT#TTTT#TTTTTTTTT#TTT#TTT#TTTTTT#TT...............................
                ................................TTTTT###TTT###TTTTT#TT#TTTTT#TTTTT#TTTTTTTTTTTTTT#TT#TTTT#T#TTT#TTTTTTTTTTTTT#T###TTTTTTTTTTT................................
                .................................TTT#TTTTT#TTTTTT#TTTTT#T#TTT#TTTT#T#TTTT###TTTTTTTTTTTTTT#TT#TTTTTTT#TTTTTTT#TTTTTTTTTTTTTT.................................
                ..................................#TT#TTTTTTT#TTTTT#TTTTTT#################################################################..................................
                ...................................TTTTTTTTTTTTTT#TTTTTTTT################################################################...................................
                ....................................#TTT#T#TT#T#T#TTTTTTTT#TTT#T##TTTTTTTTTT#TTT#TTTTTT#TTTTT#TT#TTTT#T#TT#TTTTTTTTTT#TT#....................................
                .....................................TTTTTTTTTTTTTTT#T##TT#TT#TTTTTTTTT#TTT#T#TTTTTT#TT#TT#TTTTTTTTT#T##TTTTTTTTTT#TTTT#.....................................
                ......................................TTTTTTTT#T#TTTTTTTTTT#TTT#TT#TT#TTTTTTTTTT#TTTTTTTTTTTT#TTTTT#TTTTTTTT#TTTTTTTTTT......................................
                .......................................#############################################################################TT.......................................
                ........................................#############################################################################........................................
                .........................................TTTTTTTT#T#TTTTTTTT#TTTTTTT###TTT#T###TTTT#TT##TTT#T#TTT#TTTTTT#TTTTTT#TTTT.........................................
                ..........................................TTTT##TT#TTTTT#TTT#TTTTTT#TTTTTTTTTTTTTTT##TTTTTT#TTTT#TTTT#TTTTT##TTTT#T..........................................
                ...........................................TTTTTTTTTTTTT#TTTTTT#TTTTTTTTTTTTTT##TTTTTTTTTT#TTT##T####TTTTTTTTTTTTT...........................................
                ............................................TT###################################################################............................................
                .............................................###################################################################.............................................
                ..............................................TTTTTTTTTTTTTTTTTTTT##TT#TTTTTTTTTTTTTTT#####TTTTTTT#T#TTTTTT#TTT..............................................
                ...............................................#T#TTTT#TTTT#TTTTTTTTTTTT#TTTTT#T##T#TTTTT#TT##TTTTT#TTTT##T#TT...............................................
                ................................................TTT#TTT#TTTTTTT#TTTTTTT##TTTTT##T#T#TTTTTTTTTTTTT#TTTTTTTTTTT................................................
                .................................................#########################################################TT.................................................
                ..................................................#########################################################..................................................
                ...................................................T#TTTT#TTTTTTTTTTTT#TTTTT#TTTTTT#TT##TTTTTTTTTTTTTT##TT...................................................
                ....................................................TTT#TTTT#TTTTTTTTTT#T#TTTTTTTTTTTTT#TTTT#TTTTTTTTTTTT....................................................
                .....................................................TTTTTT#TT#TTTTT#TTT#TTTTTTTTT#TTTTTTTT#TTTTTTT#TTTT.....................................................
                ......................................................TT###############################################......................................................
                .......................................................###############################################.......................................................
                ........................................................T#TTTTTTTT#TTT#TTTTTT#T#TTTTTTTTTT#TTTTTTT#TT........................................................
                .........................................................TTTTTTTTTT#T#TTTTT#TTTTTTTTTTTTTTT##TTTT#T#.........................................................
                ..........................................................TT#TTTT#TTTTTTT#T#TTTTTTTT#TTTTTTTTT#T#TT..........................................................
                ...........................................................#####################################TT...........................................................
                ............................................................#####################################............................................................
                .............................................................TTTTTT#TT#TTTT#TTTT#T##TTTTTTT#T#TT.............................................................
                ..............................................................TTTTTT#TTTT#TTTTTTTTT#TT#TTTTTT#T..............................................................
                ...............................................................#TT#T##TTT#TT#TT#TTTTTTTTTTTT#T...............................................................
                ................................................................TT###########################................................................................
                .................................................................###########################.................................................................
                ..................................................................T#TTTTTT#TTTTTTTT####TTTT..................................................................
                ...................................................................TTTTT#T#TTTT###TT##TTTT...................................................................
                ....................................................................#TTT#TTTTT#TTTTTTTTTT....................................................................
                .....................................................................#################TT.....................................................................
                ......................................................................#################......................................................................
                .......................................................................TTT##TT#TTTTTTT.......................................................................
                ........................................................................#TT###TT#TTTT........................................................................
                .........................................................................TTTTTTTTT#T.........................................................................
                ..........................................................................TT##TTT#T..........................................................................
                ...........................................................................T#T#TT#...........................................................................
                ............................................................................T##TT............................................................................
                .............................................................................T#T.............................................................................
                ..............................................................................S..............................................................................
            """.trimIndent()

            val input = rawInput.trimIndent().lines().map { it.toList() }

            var tempStart: Node<Char>? = null
            var tempEnd: Node<Char>? = null
            val graph = buildGraph(
                input, ::Node,
                includePredicate = { it in listOf('T', 'S', 'E') },
                neighborPredicate = { a: Node<*>, b: Node<*> -> false },
                callbacks = mapOf(
                    'S' to { _: Char, node: Node<Char> -> tempStart = node },
                    'E' to { _: Char, node: Node<Char> -> tempEnd = node }
                )
            )
            val start = tempStart!!
            val end = tempEnd!!

            graph.entries.forEach { (pos, node) ->
                val (r, c) = pos
                // convert row and columns to "center of the equilateral triangle" coordinates
                val rad3 = sqrt(3.0)
                val x = c.toDouble() + 1
                val y = (r.toDouble() * 3 + 1 + ((c + r) % 2)) * rad3 / 3 * -1

                // rotate 120 degrees counter clockwise around origin
                val newX = (-0.5 * x) - (rad3 / 2 * y)
                val newY = (rad3 / 2 * x) - (0.5 * y)

                // shift back to Q4
                val shiftedX = newX + (graph.width + 1) / 2
                val shiftedY = newY - (graph.height * rad3)

                // convert back to row and column
                val newC = (shiftedX - 1).roundToInt()
                val newR = ceil(shiftedY / rad3).toInt() * -1

                val potentialHops = listOf(
                    Pair(newR, newC),
                    Pair(newR, newC + 1),
                    Pair(newR, newC - 1),
                    Pair(newR + (if ((newR + newC) % 2 == 0) -1 else 1), newC)
                )
                potentialHops.forEach { neighbor ->
                    graph[neighbor]?.let { targetNode ->
                        node.neighbors.add(targetNode)
                    }
                }
            }

            val routeTable = buildRouteTable(listOf(start))
            println(routeTable[start]?.get(end))

        }
    }
}

fun main(args: Array<String>) {
    Quest20.part1()
    Quest20.part2()
    Quest20.part3()
}

