package AdventOfCodeKotlin.puzzles.EverybodyCodes2025

import kotlin.text.iterator

class Quest06 {
    companion object {
        fun part1() {
            val input =
                "ABCCbabacaACaBaAAbBcbaCcaBBAACccbBAAbacbbBabaBbaCcaCBACaCCcBAaBBAcbcaAAbaCbaCbaBAccabcbcCbCAcBbcccbb"
            var novices = 0
            var pairs = 0
            for (c in input.reversed()) {
                when (c) {
                    'A' -> {
                        pairs += novices
                    }

                    'a' -> {
                        novices++
                    }
                }
            }
            println(pairs)
        }

        fun part2() {
            val input =
                "ABCaBBBABCACbCbbCabBBbcbCbBBbcBccBaaCbacBcCBBcABccbabCbABAcAbAabAbBAcBAAAcBccbCcCcbBCCCAcbBbbbCACAaCAbabCCABaBbbaAcACBcaBaCbcbbbBabaBBBcBCbBcbbCBcACCCBbbBCccBCCaaBbCCbCBcCBaaaacbbcabCbAbBABCaacaccacbbabaBABcaCaCCCBbCBbbAaAaBCCCCcACCCCCcCaBBAcAabBabaBbaabacBCaBbabbBcABcCAACBcBAAbBAaABbbbaAbcaabbbAcbb"
            var novices = mutableMapOf<Char, Int>()
            var pairs = mutableMapOf<Char, Int>()
            for (c in input.reversed()) {
                if (c.isLowerCase()) {
                    novices[c] = novices.getOrDefault(c, 0) + 1
                }
                if (c.isUpperCase()) {
                    pairs[c] = pairs.getOrDefault(c, 0) + novices.getOrDefault(c.lowercaseChar(), 0)
                }
            }
            println(pairs.values.sum())
        }

        fun part3() {
            val input =
                "AABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCa"
            val repeats = 4L
            val distance = 1000L
            var count = 0L
            for (i in input.indices) {
                if (input[i].isLowerCase()) {
                    if (i <= distance) {
                        count += input.substring(0, (i + distance + 1).toInt())
                            .count { it == input[i].uppercaseChar() } * repeats

                        count += input.substring((i - distance).mod(input.length))
                            .count { it == input[i].uppercaseChar() } * (repeats - 1)
                    } else if (i + distance >= input.length) {
                        count += input.substring((i - distance).mod(input.length), input.length)
                            .count { it == input[i].uppercaseChar() } * repeats

                        count += input.substring(0, (i + distance).mod(input.length) + 1)
                            .count { it == input[i].uppercaseChar() } * (repeats - 1)
                    } else {
                        count += input.substring((i - distance).mod(input.length), (i + distance + 1).toInt())
                            .count { it == input[i].uppercaseChar() } * repeats
                    }
                }
            }
            println(count)
        }
    }
}

fun main() {
    Quest06.part1()
    Quest06.part2()
    Quest06.part3()
}
